# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='dominio',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='endservidor',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
