# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressoes', '0002_auto_20161205_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='gadmin',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
