# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressoes', '0003_config_gadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='ou',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
