# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressoes', '0004_config_ou'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutoriais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='logs',
            name='resumo',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
    ]
