# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressoes', '0005_auto_20161207_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoriais',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tutoriais',
            name='texto',
            field=models.CharField(max_length=10000),
        ),
    ]
