# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 13:56
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('impressoes', '0007_auto_20161207_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoriais',
            name='texto',
            field=tinymce.models.HTMLField(max_length=10000),
        ),
    ]
