# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-22 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressoes', '0008_auto_20161208_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='ip',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
