# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-30 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta_dig', models.CharField(max_length=200)),
                ('dominio', models.CharField(max_length=200)),
                ('endservidor', models.CharField(max_length=200)),
                ('gadmin', models.CharField(max_length=200)),
                ('ou', models.CharField(max_length=200)),
                ('filter', models.TextField(verbose_name='Filtro')),
            ],
        ),
        migrations.CreateModel(
            name='jobs_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('job_id', models.CharField(max_length=50)),
                ('printer', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('server', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=400)),
                ('copies', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('options', models.CharField(max_length=400)),
                ('doc', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('action', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=100)),
                ('resumo', models.CharField(max_length=300)),
                ('user', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tutoriais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('titulo', models.CharField(max_length=50)),
                ('texto', tinymce.models.HTMLField(max_length=10000)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
