# -*- coding: utf-8 -*-
"""
Django settings for Jasmine project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
<<<<<<< HEAD
from decouple import config
=======
>>>>>>> 9f532b12397d6ffd69bb2e8939b5ca4087275bcd

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD

SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
=======
SECRET_KEY = '^!c*fmy_x6z207oxe_odhw7#e(^#9zhnsw(q8quhk#!bw_xc7!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
TEMPLATE_DEBUG = False
>>>>>>> 9f532b12397d6ffd69bb2e8939b5ca4087275bcd

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'Jasmine.impressoes',
    'pagination_bootstrap',
    #'mod_wsgi.server',
=======
    'impressoes',
    'pagination_bootstrap',
    'mod_wsgi.server',
>>>>>>> 9f532b12397d6ffd69bb2e8939b5ca4087275bcd
    'django.contrib.sites',
    'django.contrib.redirects',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pagination_bootstrap.middleware.PaginationMiddleware',
]

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.contrib.auth.context_processors.auth",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.media",
    "django.core.context_processors.request",
)

ROOT_URLCONF = 'Jasmine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': [
<<<<<<< HEAD
                'Jasmine.impressoes.templatetags.impressoras_extras',
=======
                'impressoes.templatetags.impressoras_extras',
>>>>>>> 9f532b12397d6ffd69bb2e8939b5ca4087275bcd
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Jasmine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.mysql',
         'NAME': 'jasmine',
<<<<<<< HEAD
         'USER': 'root', #DIGITE USUARIO DO BANCO 
         'PASSWORD': 'root', #DIGITE SENHA DO BANCO
=======
         'USER': 'USER', #DIGITE USUARIO DO BANCO 
         'PASSWORD': 'PASS', #DIGITE SENHA DO BANCO
>>>>>>> 9f532b12397d6ffd69bb2e8939b5ca4087275bcd
         'HOST': 'localhost',
         'PORT': '3306'
         }
     }

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'pt-br'

DATE_FORMAT = 'd/m/Y'

<<<<<<< HEAD
TIME_ZONE = 'America/Araguaina'
=======
TIME_ZONE = 'UTC'
>>>>>>> 9f532b12397d6ffd69bb2e8939b5ca4087275bcd

USE_I18N = True

USE_L10N = True

<<<<<<< HEAD
USE_TZ = False
=======
USE_TZ = True
>>>>>>> 9f532b12397d6ffd69bb2e8939b5ca4087275bcd

DATE_INPUT_FORMATS = (
    '%d/%m/%Y',
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/


STATIC_URL = '/jasmine/static/'

<<<<<<< HEAD
STATIC_ROOT = os.path.join(BASE_DIR, 'impressoes/static')
=======
STATIC_ROOT = '/home/cgti/Jasmine/impressoes/static'
>>>>>>> 9f532b12397d6ffd69bb2e8939b5ca4087275bcd
